# Generated by Django 5.0.6 on 2024-07-17 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('vigente', models.BooleanField()),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('motor', models.CharField(blank=True, max_length=100, null=True)),
                ('potencia', models.IntegerField(blank=True, null=True)),
                ('traccion', models.CharField(blank=True, max_length=10, null=True)),
                ('aire_acondicionado', models.BooleanField(blank=True, null=True)),
                ('alimentacion', models.CharField(blank=True, max_length=20, null=True)),
                ('neumaticos', models.CharField(blank=True, max_length=20, null=True)),
                ('caracteristica_1_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristica_1_descripcion', models.TextField(blank=True, null=True)),
                ('caracteristica_2_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristica_2_descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproducto')),
            ],
        ),
    ]
