# Generated by Django 5.0.6 on 2024-07-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='caracteristica_1_descripcion',
            new_name='caracteristica',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='aire_acondicionado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='caracteristica_1_titulo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='caracteristica_2_descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='caracteristica_2_titulo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
    ]
