# Generated by Django 5.0.6 on 2024-07-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_caracteristica_1_descripcion_producto_caracteristica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='equipamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
