# Generated by Django 5.0.7 on 2024-07-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mensaje_delete_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='tema',
            new_name='asunto',
        ),
    ]
