# Generated by Django 5.0.7 on 2024-07-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_tema_mensaje_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='potencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
