# Generated by Django 5.0.6 on 2024-07-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_producto_imagen_alter_producto_potencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='potencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
